sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_point
  max_range: 10.0
  max_update_rate: 10.0
  padding_offset: 0.1
  padding_scale: 0.1
  point_cloud_topic: /point
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater