# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - moveit_control

  moveit_control:
    type: FollowJointTrajectory
    joints:
      - cabin_joint
      - arm_one_joint
      - arm_two_joint
      - ladle_joint
    action_ns: follow_joint_trajectory
    default: true